CONTENT_TYPE_JSON = "application/json"

DEFAULT_ALLOWED_POINT_MAX_ATTEMPTS = 5_000
DEFAULT_DISPATCH_TIMEOUT_SECONDS = 10.0
DEFAULT_DISPATCH_URL = "https://live-data-1015949672422.europe-west1.run.app/api/dispatch"
DEFAULT_JSON_OUTPUT_INDENT = 2
DEFAULT_POSTGRES_AIRCRAFT_TABLE = "aircraft"
DEFAULT_POSTGRES_EVENT_TABLE = "event"
DEFAULT_POSTGRES_POLYGON_TABLE = "polygon"
DEFAULT_POSTGRES_PORT = 5432
DEFAULT_POSTGRES_SCHEMA = "public"
DEFAULT_SIMULATION_FLIGHT_COUNT = 1
DEFAULT_SIMULATION_INTERVAL_SECONDS = 30.0
DEFAULT_UNUSED_EVENT_ID_MAX_ATTEMPTS = 1_000

ENV_ALLOWED_POINT_MAX_ATTEMPTS = "FLIGHT_GENERATOR_ALLOWED_POINT_MAX_ATTEMPTS"
ENV_DISPATCH_TIMEOUT_SECONDS = "FLIGHT_GENERATOR_DISPATCH_TIMEOUT_SECONDS"
ENV_DISPATCH_URL = "FLIGHT_GENERATOR_DISPATCH_URL"
ENV_JSON_OUTPUT_INDENT = "FLIGHT_GENERATOR_OUTPUT_JSON_INDENT"
ENV_POSTGRES_AIRCRAFT_TABLE = "FLIGHT_GENERATOR_POSTGRES_AIRCRAFT_TABLE"
ENV_POSTGRES_BUSY_STATUS = "FLIGHT_GENERATOR_AIRCRAFT_BUSY_STATUS"
ENV_POSTGRES_DBNAME = "FLIGHT_GENERATOR_POSTGRES_DBNAME"
ENV_POSTGRES_EVENT_TABLE = "FLIGHT_GENERATOR_POSTGRES_EVENT_TABLE"
ENV_POSTGRES_HOST = "FLIGHT_GENERATOR_POSTGRES_HOST"
ENV_POSTGRES_PASSWORD = "FLIGHT_GENERATOR_POSTGRES_PASSWORD"
ENV_POSTGRES_POLYGON_TABLE = "FLIGHT_GENERATOR_POSTGRES_POLYGON_TABLE"
ENV_POSTGRES_PORT = "FLIGHT_GENERATOR_POSTGRES_PORT"
ENV_POSTGRES_SCHEMA = "FLIGHT_GENERATOR_POSTGRES_SCHEMA"
ENV_POSTGRES_SSLMODE = "FLIGHT_GENERATOR_POSTGRES_SSLMODE"
ENV_POSTGRES_USER = "FLIGHT_GENERATOR_POSTGRES_USER"
ENV_SIMULATION_FLIGHT_COUNT = "FLIGHT_GENERATOR_NUM_FLIGHTS"
ENV_SIMULATION_INTERVAL_SECONDS = "FLIGHT_GENERATOR_RUN_INTERVAL_SECONDS"
ENV_UNUSED_EVENT_ID_MAX_ATTEMPTS = "FLIGHT_GENERATOR_UNUSED_EVENT_ID_MAX_ATTEMPTS"
ENV_POSTGRES_FREE_STATUS = "FLIGHT_GENERATOR_AIRCRAFT_FREE_STATUS"

REGION_GEOJSON_FILE_NAME = "israel_gaza_west_bank.geojson"

STATUS_BUSY = "BUSY"
STATUS_FREE = "FREE"

URGENCY_LEVELS = ("LOW", "MID", "HIGH")
