# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=XJ6JCV33YE3CRQTL
sasl.password=cfltLYznedQAaHRGbPiiJ4nktPhLNA4Jymg77xBVMLo4mdeilZXqIubfBqP6Metg

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-09a97227-e44e-43fc-9100-a7057ce887f4
